// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../client_to_server/handshake/initial_pqc_keys.dart';
import '../client_to_server/response.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AdditionalAccount {
  final PlatformInt64 userId;
  final String planId;

  const AdditionalAccount({
    required this.userId,
    required this.planId,
  });

  @override
  int get hashCode => userId.hashCode ^ planId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdditionalAccount &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          planId == other.planId;
}

class MemoriesUploadUrls {
  final String mediaId;
  final PresignedPost? thumbnailUpload;
  final PresignedPost? fullUpload;

  const MemoriesUploadUrls({
    required this.mediaId,
    this.thumbnailUpload,
    this.fullUpload,
  });

  @override
  int get hashCode =>
      mediaId.hashCode ^ thumbnailUpload.hashCode ^ fullUpload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoriesUploadUrls &&
          runtimeType == other.runtimeType &&
          mediaId == other.mediaId &&
          thumbnailUpload == other.thumbnailUpload &&
          fullUpload == other.fullUpload;
}

class MemoriesUsage {
  final PlatformInt64 maxBytes;
  final PlatformInt64 currentBytes;
  final PlatformInt64 count;

  const MemoriesUsage({
    required this.maxBytes,
    required this.currentBytes,
    required this.count,
  });

  @override
  int get hashCode =>
      maxBytes.hashCode ^ currentBytes.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoriesUsage &&
          runtimeType == other.runtimeType &&
          maxBytes == other.maxBytes &&
          currentBytes == other.currentBytes &&
          count == other.count;
}

class PasswordlessNotificationMessage {
  final PlatformInt64 id;
  final Uint8List encryptedMessage;

  const PasswordlessNotificationMessage({
    required this.id,
    required this.encryptedMessage,
  });

  @override
  int get hashCode => id.hashCode ^ encryptedMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasswordlessNotificationMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          encryptedMessage == other.encryptedMessage;
}

class PlanBallance {
  final PlatformInt64 usedDailyMediaUploadLimit;
  final PlatformInt64 usedUploadMediaSizeLimit;
  final PlatformInt64? paymentPeriodDays;
  final PlatformInt64? lastPaymentDoneUnixTimestamp;
  final List<Transaction> transactions;
  final List<AdditionalAccount> additionalAccounts;
  final bool? autoRenewal;
  final PlatformInt64? additionalAccountOwnerId;

  const PlanBallance({
    required this.usedDailyMediaUploadLimit,
    required this.usedUploadMediaSizeLimit,
    this.paymentPeriodDays,
    this.lastPaymentDoneUnixTimestamp,
    required this.transactions,
    required this.additionalAccounts,
    this.autoRenewal,
    this.additionalAccountOwnerId,
  });

  @override
  int get hashCode =>
      usedDailyMediaUploadLimit.hashCode ^
      usedUploadMediaSizeLimit.hashCode ^
      paymentPeriodDays.hashCode ^
      lastPaymentDoneUnixTimestamp.hashCode ^
      transactions.hashCode ^
      additionalAccounts.hashCode ^
      autoRenewal.hashCode ^
      additionalAccountOwnerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlanBallance &&
          runtimeType == other.runtimeType &&
          usedDailyMediaUploadLimit == other.usedDailyMediaUploadLimit &&
          usedUploadMediaSizeLimit == other.usedUploadMediaSizeLimit &&
          paymentPeriodDays == other.paymentPeriodDays &&
          lastPaymentDoneUnixTimestamp == other.lastPaymentDoneUnixTimestamp &&
          transactions == other.transactions &&
          additionalAccounts == other.additionalAccounts &&
          autoRenewal == other.autoRenewal &&
          additionalAccountOwnerId == other.additionalAccountOwnerId;
}

class PqcBundle {
  final PlatformInt64 eccSignedPrekeyId;
  final Uint8List eccSignedPrekey;
  final Uint8List eccSignedPrekeySignature;
  final PlatformInt64 kyberSignedPrekeyId;
  final Uint8List kyberSignedPrekey;
  final Uint8List kyberSignedPrekeySignature;
  final PqcPreKey? prekey;

  const PqcBundle({
    required this.eccSignedPrekeyId,
    required this.eccSignedPrekey,
    required this.eccSignedPrekeySignature,
    required this.kyberSignedPrekeyId,
    required this.kyberSignedPrekey,
    required this.kyberSignedPrekeySignature,
    this.prekey,
  });

  @override
  int get hashCode =>
      eccSignedPrekeyId.hashCode ^
      eccSignedPrekey.hashCode ^
      eccSignedPrekeySignature.hashCode ^
      kyberSignedPrekeyId.hashCode ^
      kyberSignedPrekey.hashCode ^
      kyberSignedPrekeySignature.hashCode ^
      prekey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PqcBundle &&
          runtimeType == other.runtimeType &&
          eccSignedPrekeyId == other.eccSignedPrekeyId &&
          eccSignedPrekey == other.eccSignedPrekey &&
          eccSignedPrekeySignature == other.eccSignedPrekeySignature &&
          kyberSignedPrekeyId == other.kyberSignedPrekeyId &&
          kyberSignedPrekey == other.kyberSignedPrekey &&
          kyberSignedPrekeySignature == other.kyberSignedPrekeySignature &&
          prekey == other.prekey;
}

class PresignedPost {
  final String url;
  final Map<String, String> fields;

  const PresignedPost({
    required this.url,
    required this.fields,
  });

  @override
  int get hashCode => url.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresignedPost &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          fields == other.fields;
}

class ProofOfWork {
  final String prefix;
  final PlatformInt64 difficulty;

  const ProofOfWork({
    required this.prefix,
    required this.difficulty,
  });

  @override
  int get hashCode => prefix.hashCode ^ difficulty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProofOfWork &&
          runtimeType == other.runtimeType &&
          prefix == other.prefix &&
          difficulty == other.difficulty;
}

class Transaction {
  const Transaction();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Transaction && runtimeType == other.runtimeType;
}

class UserData {
  final PlatformInt64 userId;
  final List<PreKey> prekeys;
  final Uint8List? username;
  final Uint8List? publicIdentityKey;
  final Uint8List? signedPrekey;
  final Uint8List? signedPrekeySignature;
  final PlatformInt64? signedPrekeyId;
  final PlatformInt64? registrationId;
  final PqcBundle? pqcBundle;

  const UserData({
    required this.userId,
    required this.prekeys,
    this.username,
    this.publicIdentityKey,
    this.signedPrekey,
    this.signedPrekeySignature,
    this.signedPrekeyId,
    this.registrationId,
    this.pqcBundle,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      prekeys.hashCode ^
      username.hashCode ^
      publicIdentityKey.hashCode ^
      signedPrekey.hashCode ^
      signedPrekeySignature.hashCode ^
      signedPrekeyId.hashCode ^
      registrationId.hashCode ^
      pqcBundle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserData &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          prekeys == other.prekeys &&
          username == other.username &&
          publicIdentityKey == other.publicIdentityKey &&
          signedPrekey == other.signedPrekey &&
          signedPrekeySignature == other.signedPrekeySignature &&
          signedPrekeyId == other.signedPrekeyId &&
          registrationId == other.registrationId &&
          pqcBundle == other.pqcBundle;
}
