include: package:very_good_analysis/analysis_options.yaml

analyzer: 
  errors:
    always_use_package_imports: ignore
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    avoid_function_literals_in_foreach_calls: ignore
    avoid_setters_without_getters: ignore
    inference_failure_on_instance_creation: ignore
    avoid_positional_boolean_parameters: ignore
    inference_failure_on_collection_literal: ignore
    matching_super_parameters: ignore
  exclude: 
    - "lib/src/model/protobuf/**"
    - "lib/src/model/protobuf/api/websocket/**"
    - "lib/generated/**"
    - "dependencies/**"
    - "test/drift/**"
    - "**.g.dart"

linter:
  rules:
    public_member_api_docs: false
    avoid_catches_without_on_clauses: false
    document_ignores: false
