// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FlutterKeyManager {
  const FlutterKeyManager();

  static Future<Uint8List> getLoginToken() => RustLib.instance.api
      .crateBridgeWrapperKeyManagerFlutterKeyManagerGetLoginToken();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterKeyManager && runtimeType == other.runtimeType;
}
