// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FlutterUserDiscovery {
  const FlutterUserDiscovery();

  static Future<Uint8List> getCurrentVersion() => RustLib.instance.api
      .crateBridgeWrapperUserDiscoveryFlutterUserDiscoveryGetCurrentVersion();

  static Future<List<Uint8List>> getNewMessages({
    required PlatformInt64 contactId,
    required List<int> receivedVersion,
  }) => RustLib.instance.api
      .crateBridgeWrapperUserDiscoveryFlutterUserDiscoveryGetNewMessages(
        contactId: contactId,
        receivedVersion: receivedVersion,
      );

  static Future<void> handleNewMessages({
    required PlatformInt64 contactId,
    PlatformInt64? publicKeyVerifiedTimestamp,
    required List<Uint8List> messages,
  }) => RustLib.instance.api
      .crateBridgeWrapperUserDiscoveryFlutterUserDiscoveryHandleNewMessages(
        contactId: contactId,
        publicKeyVerifiedTimestamp: publicKeyVerifiedTimestamp,
        messages: messages,
      );

  static Future<void> initializeOrUpdate({
    required int threshold,
    required PlatformInt64 userId,
    required List<int> publicKey,
    required bool sharePromotion,
  }) => RustLib.instance.api
      .crateBridgeWrapperUserDiscoveryFlutterUserDiscoveryInitializeOrUpdate(
        threshold: threshold,
        userId: userId,
        publicKey: publicKey,
        sharePromotion: sharePromotion,
      );

  static Future<Uint8List?> shouldRequestNewMessages({
    required PlatformInt64 contactId,
    required List<int> version,
  }) => RustLib.instance.api
      .crateBridgeWrapperUserDiscoveryFlutterUserDiscoveryShouldRequestNewMessages(
        contactId: contactId,
        version: version,
      );

  static Future<void> updateVerificationStateForUser({
    required PlatformInt64 contactId,
    PlatformInt64? publicKeyVerifiedTimestamp,
  }) => RustLib.instance.api
      .crateBridgeWrapperUserDiscoveryFlutterUserDiscoveryUpdateVerificationStateForUser(
        contactId: contactId,
        publicKeyVerifiedTimestamp: publicKeyVerifiedTimestamp,
      );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterUserDiscovery && runtimeType == other.runtimeType;
}
