// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FlutterUserDiscovery {
  const FlutterUserDiscovery();

  static Future<void> changeExclusionForContact({
    required int callbackId,
    required PlatformInt64 contactId,
    required bool exclude,
  }) => RustLib.instance.api
      .crateBridgeWrapperUserDiscoveryFlutterUserDiscoveryChangeExclusionForContact(
        callbackId: callbackId,
        contactId: contactId,
        exclude: exclude,
      );

  /// UI-facing read used to display the current discovery version.
  static Future<Uint8List> getCurrentVersion({required int callbackId}) =>
      RustLib.instance.api
          .crateBridgeWrapperUserDiscoveryFlutterUserDiscoveryGetCurrentVersion(
            callbackId: callbackId,
          );

  /// UI-facing hook used when a user manually changes contact verification.
  static Future<void> updateVerificationStateForUser({
    required int callbackId,
    required PlatformInt64 contactId,
    PlatformInt64? publicKeyVerifiedTimestamp,
  }) => RustLib.instance.api
      .crateBridgeWrapperUserDiscoveryFlutterUserDiscoveryUpdateVerificationStateForUser(
        callbackId: callbackId,
        contactId: contactId,
        publicKeyVerifiedTimestamp: publicKeyVerifiedTimestamp,
      );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterUserDiscovery && runtimeType == other.runtimeType;
}
