// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CustomAvatarInfo {
  final Uint8List? webp;
  final Uint8List? sha256;
  final int? width;
  final int? height;
  final bool acceptedContactsOnly;
  final PlatformInt64 sourceRevision;

  const CustomAvatarInfo({
    this.webp,
    this.sha256,
    this.width,
    this.height,
    required this.acceptedContactsOnly,
    required this.sourceRevision,
  });

  @override
  int get hashCode =>
      webp.hashCode ^
      sha256.hashCode ^
      width.hashCode ^
      height.hashCode ^
      acceptedContactsOnly.hashCode ^
      sourceRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomAvatarInfo &&
          runtimeType == other.runtimeType &&
          webp == other.webp &&
          sha256 == other.sha256 &&
          width == other.width &&
          height == other.height &&
          acceptedContactsOnly == other.acceptedContactsOnly &&
          sourceRevision == other.sourceRevision;
}
