// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Why a media send stopped at `fileLimitReached`, for the chat entry to show.
class MediaSizeReport {
  /// The encoded media as it sits on disk, while it is still there.
  final PlatformInt64? mediaBytes;

  /// The largest single object the user's plan accepts.
  final PlatformInt64? limitBytes;

  const MediaSizeReport({
    this.mediaBytes,
    this.limitBytes,
  });

  @override
  int get hashCode => mediaBytes.hashCode ^ limitBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaSizeReport &&
          runtimeType == other.runtimeType &&
          mediaBytes == other.mediaBytes &&
          limitBytes == other.limitBytes;
}
