// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class StickerOutput {
  final Uint8List webp;
  final Uint8List sha256;
  final String contentHash;
  final int width;
  final int height;

  const StickerOutput({
    required this.webp,
    required this.sha256,
    required this.contentHash,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      webp.hashCode ^
      sha256.hashCode ^
      contentHash.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StickerOutput &&
          runtimeType == other.runtimeType &&
          webp == other.webp &&
          sha256 == other.sha256 &&
          contentHash == other.contentHash &&
          width == other.width &&
          height == other.height;
}
