// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SqlExecutionResult {
  final PlatformInt64 affectedRows;
  final PlatformInt64 lastInsertRowId;

  const SqlExecutionResult({
    required this.affectedRows,
    required this.lastInsertRowId,
  });

  @override
  int get hashCode => affectedRows.hashCode ^ lastInsertRowId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SqlExecutionResult &&
          runtimeType == other.runtimeType &&
          affectedRows == other.affectedRows &&
          lastInsertRowId == other.lastInsertRowId;
}

class SqlRow {
  final List<SqlValue> values;

  const SqlRow({
    required this.values,
  });

  @override
  int get hashCode => values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SqlRow &&
          runtimeType == other.runtimeType &&
          values == other.values;
}

class SqlRows {
  final List<String> columns;
  final List<SqlRow> rows;

  const SqlRows({
    required this.columns,
    required this.rows,
  });

  @override
  int get hashCode => columns.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SqlRows &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          rows == other.rows;
}

class SqlValue {
  /// 0 = null, 1 = integer, 2 = real, 3 = text, 4 = blob.
  final int kind;
  final PlatformInt64? integerValue;
  final double? realValue;
  final String? textValue;
  final Uint8List? blobValue;

  const SqlValue({
    required this.kind,
    this.integerValue,
    this.realValue,
    this.textValue,
    this.blobValue,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      integerValue.hashCode ^
      realValue.hashCode ^
      textValue.hashCode ^
      blobValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SqlValue &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          integerValue == other.integerValue &&
          realValue == other.realValue &&
          textValue == other.textValue &&
          blobValue == other.blobValue;
}
