// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../bridge.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_callbacks`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FlutterCallbacks`, `Logging`, `UserDiscoveryCallbacks`

Future<void> initFlutterCallbacks({
  required FutureOr<RustStreamSink<String>> Function() loggingGetStreamSink,
  required FutureOr<Uint8List?> Function(Uint8List) userDiscoverySignData,
  required FutureOr<bool> Function(Uint8List, Uint8List, Uint8List)
  userDiscoveryVerifySignature,
  required FutureOr<bool> Function(PlatformInt64, Uint8List)
  userDiscoveryVerifyStoredPubkey,
  required FutureOr<bool> Function(List<Uint8List>) userDiscoverySetShares,
  required FutureOr<Uint8List?> Function(PlatformInt64)
  userDiscoveryGetShareForContact,
  required FutureOr<bool> Function(PlatformInt64, PlatformInt64, Uint8List)
  userDiscoveryPushOwnPromotionAndClearOldVersion,
  required FutureOr<List<Uint8List>?> Function(PlatformInt64)
  userDiscoveryGetOwnPromotionsAfterVersion,
  required FutureOr<bool> Function(OtherPromotion)
  userDiscoveryStoreOtherPromotion,
  required FutureOr<List<OtherPromotion>?> Function(PlatformInt64)
  userDiscoveryGetOtherPromotionsByPublicId,
  required FutureOr<AnnouncedUser?> Function(PlatformInt64)
  userDiscoveryGetAnnouncedUserByPublicId,
  required FutureOr<Uint8List?> Function(PlatformInt64)
  userDiscoveryGetContactVersion,
  required FutureOr<bool> Function(PlatformInt64, Uint8List)
  userDiscoverySetContactVersion,
  required FutureOr<bool> Function(PlatformInt64, AnnouncedUser, PlatformInt64?)
  userDiscoveryPushNewUserRelation,
  required FutureOr<Uint8List?> Function(PlatformInt64)
  userDiscoveryGetContactPromotion,
}) => RustLib.instance.api.crateBridgeCallbacksInitFlutterCallbacks(
  loggingGetStreamSink: loggingGetStreamSink,
  userDiscoverySignData: userDiscoverySignData,
  userDiscoveryVerifySignature: userDiscoveryVerifySignature,
  userDiscoveryVerifyStoredPubkey: userDiscoveryVerifyStoredPubkey,
  userDiscoverySetShares: userDiscoverySetShares,
  userDiscoveryGetShareForContact: userDiscoveryGetShareForContact,
  userDiscoveryPushOwnPromotionAndClearOldVersion:
      userDiscoveryPushOwnPromotionAndClearOldVersion,
  userDiscoveryGetOwnPromotionsAfterVersion:
      userDiscoveryGetOwnPromotionsAfterVersion,
  userDiscoveryStoreOtherPromotion: userDiscoveryStoreOtherPromotion,
  userDiscoveryGetOtherPromotionsByPublicId:
      userDiscoveryGetOtherPromotionsByPublicId,
  userDiscoveryGetAnnouncedUserByPublicId:
      userDiscoveryGetAnnouncedUserByPublicId,
  userDiscoveryGetContactVersion: userDiscoveryGetContactVersion,
  userDiscoverySetContactVersion: userDiscoverySetContactVersion,
  userDiscoveryPushNewUserRelation: userDiscoveryPushNewUserRelation,
  userDiscoveryGetContactPromotion: userDiscoveryGetContactPromotion,
);
