// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> createNewGroup({
  required String groupName,
  required Int64List memberIds,
}) => RustLib.instance.api.crateBridgeGroupsCreateNewGroup(
  groupName: groupName,
  memberIds: memberIds,
);

Future<bool> fetchGroupState({required String groupId}) =>
    RustLib.instance.api.crateBridgeGroupsFetchGroupState(groupId: groupId);

Future<bool> addHiddenContact({required PlatformInt64 contactId}) => RustLib
    .instance
    .api
    .crateBridgeGroupsAddHiddenContact(contactId: contactId);

Future<void> fetchGroupStatesForUnjoinedGroups() =>
    RustLib.instance.api.crateBridgeGroupsFetchGroupStatesForUnjoinedGroups();

Future<void> fetchMissingGroupPublicKeys({
  String? groupId,
  required bool force,
}) => RustLib.instance.api.crateBridgeGroupsFetchMissingGroupPublicKeys(
  groupId: groupId,
  force: force,
);

Future<bool> manageAdminState({
  required String groupId,
  required PlatformInt64 contactId,
  required bool remove,
}) => RustLib.instance.api.crateBridgeGroupsManageAdminState(
  groupId: groupId,
  contactId: contactId,
  remove: remove,
);

Future<bool> updateGroupName({
  required String groupId,
  required String groupName,
}) => RustLib.instance.api.crateBridgeGroupsUpdateGroupName(
  groupId: groupId,
  groupName: groupName,
);

Future<bool> updateChatDeletionTime({
  required String groupId,
  required PlatformInt64 deleteMessagesAfterMilliseconds,
}) => RustLib.instance.api.crateBridgeGroupsUpdateChatDeletionTime(
  groupId: groupId,
  deleteMessagesAfterMilliseconds: deleteMessagesAfterMilliseconds,
);

Future<bool> addNewGroupMembers({
  required String groupId,
  required Int64List memberIds,
}) => RustLib.instance.api.crateBridgeGroupsAddNewGroupMembers(
  groupId: groupId,
  memberIds: memberIds,
);

Future<bool> removeMemberFromGroup({
  required String groupId,
  required PlatformInt64 contactId,
}) => RustLib.instance.api.crateBridgeGroupsRemoveMemberFromGroup(
  groupId: groupId,
  contactId: contactId,
);

Future<bool> leaveGroup({required String groupId}) =>
    RustLib.instance.api.crateBridgeGroupsLeaveGroup(groupId: groupId);
