// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../user_config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class UserConfigApi {
  const UserConfigApi();

  static UserConfig clone({required UserConfig config}) => RustLib.instance.api
      .crateBridgeUserConfigUserConfigApiClone(config: config);

  static Future<UserConfig> create({
    required PlatformInt64 userId,
    required String username,
    required String displayName,
    String? currentSetupPage,
    required PlatformInt64 appVersion,
  }) => RustLib.instance.api.crateBridgeUserConfigUserConfigApiCreate(
    userId: userId,
    username: username,
    displayName: displayName,
    currentSetupPage: currentSetupPage,
    appVersion: appVersion,
  );

  static Future<UserConfig> importJson({required String json}) => RustLib
      .instance
      .api
      .crateBridgeUserConfigUserConfigApiImportJson(json: json);

  static Future<UserConfig?> load() =>
      RustLib.instance.api.crateBridgeUserConfigUserConfigApiLoad();

  static Future<UserConfig> save({required UserConfig config}) => RustLib
      .instance
      .api
      .crateBridgeUserConfigUserConfigApiSave(config: config);

  static Future<UserConfig> update({
    required UserConfig base,
    required UserConfig config,
  }) => RustLib.instance.api.crateBridgeUserConfigUserConfigApiUpdate(
    base: base,
    config: config,
  );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserConfigApi && runtimeType == other.runtimeType;
}
