// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BackupPasswordKeys {
  final U8Array32 backupId;
  final U8Array32 encryptionKey;

  const BackupPasswordKeys({
    required this.backupId,
    required this.encryptionKey,
  });

  @override
  int get hashCode => backupId.hashCode ^ encryptionKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupPasswordKeys &&
          runtimeType == other.runtimeType &&
          backupId == other.backupId &&
          encryptionKey == other.encryptionKey;
}
