// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PasswordLessRecovery {
  final Uint8List? recoverySecretShare;
  final bool delete;
  final PlatformInt64 threshold;

  const PasswordLessRecovery({
    this.recoverySecretShare,
    required this.delete,
    required this.threshold,
  });

  @override
  int get hashCode =>
      recoverySecretShare.hashCode ^ delete.hashCode ^ threshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasswordLessRecovery &&
          runtimeType == other.runtimeType &&
          recoverySecretShare == other.recoverySecretShare &&
          delete == other.delete &&
          threshold == other.threshold;
}
