// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BackupFileSize {
  final String name;

  /// None means the source file is absent and will be skipped by the backup.
  final PlatformInt64? sizeBytes;

  const BackupFileSize({
    required this.name,
    this.sizeBytes,
  });

  @override
  int get hashCode => name.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupFileSize &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          sizeBytes == other.sizeBytes;
}

class BackupStorageInfo {
  final PlatformInt64 databaseSizeBytes;
  final PlatformInt64 freeSizeBytes;
  final List<BackupTableSize> tables;
  final List<BackupFileSize> files;

  const BackupStorageInfo({
    required this.databaseSizeBytes,
    required this.freeSizeBytes,
    required this.tables,
    required this.files,
  });

  @override
  int get hashCode =>
      databaseSizeBytes.hashCode ^
      freeSizeBytes.hashCode ^
      tables.hashCode ^
      files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupStorageInfo &&
          runtimeType == other.runtimeType &&
          databaseSizeBytes == other.databaseSizeBytes &&
          freeSizeBytes == other.freeSizeBytes &&
          tables == other.tables &&
          files == other.files;
}

class BackupTableSize {
  final String name;
  final PlatformInt64 rows;
  final PlatformInt64 tableSizeBytes;
  final PlatformInt64 indexSizeBytes;

  const BackupTableSize({
    required this.name,
    required this.rows,
    required this.tableSizeBytes,
    required this.indexSizeBytes,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      rows.hashCode ^
      tableSizeBytes.hashCode ^
      indexSizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupTableSize &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          rows == other.rows &&
          tableSizeBytes == other.tableSizeBytes &&
          indexSizeBytes == other.indexSizeBytes;
}
