// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PreKey {
  final PlatformInt64 id;
  final Uint8List prekey;

  const PreKey({
    required this.id,
    required this.prekey,
  });

  @override
  int get hashCode => id.hashCode ^ prekey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreKey &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          prekey == other.prekey;
}
