[package]
name = "rust_lib_twonly"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[dependencies]
flutter_rust_bridge = { version = "=2.12.0", features = ["chrono"] }
thiserror = "2.0.18"
sqlx = { version = "0.9.0-alpha.1", default-features = false, features = [
    "runtime-tokio",
    "sqlite",
    "migrate",
    "macros",
    "chrono",
    "derive",
    "json",
] }
libsqlite3-sys = { version = "0.35.0", features = [
    "bundled-sqlcipher-vendored-openssl",
] }
tokio = { version = "1.44", features = ["full", "macros"] }
tracing = "0.1.44"
prost = "0.14.1"
blahaj = "0.6.0"
serde_json = "1.0"
base64 = "0.22.1"
hmac = "0.12.1"
hkdf = "0.12.4"
sha2 = "0.10.8"
aes-gcm = "0.10.3"
chacha20poly1305 = "0.10.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
paste = "1.0.15"
serde = { version = "1.0", features = ["derive"] }
zeroize = { version = "1.8", features = ["derive"] }
hex = "0.4.3"
keyring-core = "1"
postcard = { version = "1.0", features = ["alloc"] }
chrono = { version = "0.4", features = ["serde"] }
zip = { version = "2.2.2", default-features = false, features = ["deflate"] }
scrypt = { version = "0.12", default-features = false }
walkdir = "2.5.0"
libsignal-protocol = { git = "https://github.com/signalapp/libsignal", version = "0.1.0", rev = "44a6dd8fc9f9d6903b32842b80b3894a75678418" }
rand08 = { version = "0.8.5", package = "rand" }
rand = "0.9.4"
uuid = { version = "1", features = ["v4", "v7"] }
flate2 = "1"
resvg = { version = "0.45", default-features = false, features = ["text"] }
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
] }
async-trait = "0.1.91"
futures-util = "0.3.31"
tokio-tungstenite = { version = "0.28.0", default-features = false, features = [
    "connect",
    "rustls-tls-native-roots",
] }
rustls = { version = "0.23.43", default-features = false, features = [
    "ring",
    "std",
] }
tokio-util = "0.7.16"
bon = "3.9.3"
stream-tungstenite = "0.6.1"
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "gif", "bmp", "webp"] }
webp = "0.3.1"
[target.'cfg(target_os = "ios")'.dependencies]
# iOS backend: Requires the 'protected' feature for Data Protection Keychain
apple-native-keyring-store = { version = "1", features = ["protected"] }
libc = "0.2"
[target.'cfg(target_os = "android")'.dependencies]
# Android backend: Interfaces with the Android Keystore
android-native-keyring-store = "1"
jni = "0.21.1"

[dev-dependencies]
anyhow = "1.0.104"
pretty_env_logger = "0.5.0"
tempfile = "3.27.0"


[build-dependencies]
prost-build = "0.14.1"
