// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unnecessary_import, non_constant_identifier_names

// Static analysis wrongly picks the IO variant, thus ignore this

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

import 'bridge.dart';
import 'bridge/callbacks.dart';
import 'bridge/wrapper/user_discovery.dart';
import 'frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FutureOr<RustStreamSink<String>> Function()
  dco_decode_DartFn_Inputs__Output_StreamSink_String_Sse_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<AnnouncedUser?> Function(PlatformInt64)
  dco_decode_DartFn_Inputs_i_64_Output_opt_box_autoadd_announced_user_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<List<Uint8List>?> Function(PlatformInt64)
  dco_decode_DartFn_Inputs_i_64_Output_opt_list_list_prim_u_8_strict_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<List<OtherPromotion>?> Function(PlatformInt64)
  dco_decode_DartFn_Inputs_i_64_Output_opt_list_other_promotion_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<Uint8List?> Function(PlatformInt64)
  dco_decode_DartFn_Inputs_i_64_Output_opt_list_prim_u_8_strict_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<bool> Function(PlatformInt64, AnnouncedUser, PlatformInt64?)
  dco_decode_DartFn_Inputs_i_64_announced_user_opt_box_autoadd_i_64_Output_bool_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<bool> Function(PlatformInt64, PlatformInt64, Uint8List)
  dco_decode_DartFn_Inputs_i_64_i_64_list_prim_u_8_strict_Output_bool_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<bool> Function(PlatformInt64, Uint8List)
  dco_decode_DartFn_Inputs_i_64_list_prim_u_8_strict_Output_bool_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<bool> Function(List<Uint8List>)
  dco_decode_DartFn_Inputs_list_list_prim_u_8_strict_Output_bool_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<Uint8List?> Function(Uint8List)
  dco_decode_DartFn_Inputs_list_prim_u_8_strict_Output_opt_list_prim_u_8_strict_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<bool> Function(Uint8List, Uint8List, Uint8List)
  dco_decode_DartFn_Inputs_list_prim_u_8_strict_list_prim_u_8_strict_list_prim_u_8_strict_Output_bool_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<bool> Function(OtherPromotion)
  dco_decode_DartFn_Inputs_other_promotion_Output_bool_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnnouncedUser dco_decode_announced_user(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AnnouncedUser dco_decode_box_autoadd_announced_user(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  TwonlyConfig dco_decode_box_autoadd_twonly_config(dynamic raw);

  @protected
  FlutterUserDiscovery dco_decode_flutter_user_discovery(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<OtherPromotion> dco_decode_list_other_promotion(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  AnnouncedUser? dco_decode_opt_box_autoadd_announced_user(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  List<Uint8List>? dco_decode_opt_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<OtherPromotion>? dco_decode_opt_list_other_promotion(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  OtherPromotion dco_decode_other_promotion(dynamic raw);

  @protected
  TwonlyConfig dco_decode_twonly_config(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnnouncedUser sse_decode_announced_user(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AnnouncedUser sse_decode_box_autoadd_announced_user(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  TwonlyConfig sse_decode_box_autoadd_twonly_config(
    SseDeserializer deserializer,
  );

  @protected
  FlutterUserDiscovery sse_decode_flutter_user_discovery(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<OtherPromotion> sse_decode_list_other_promotion(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  AnnouncedUser? sse_decode_opt_box_autoadd_announced_user(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  List<Uint8List>? sse_decode_opt_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<OtherPromotion>? sse_decode_opt_list_other_promotion(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OtherPromotion sse_decode_other_promotion(SseDeserializer deserializer);

  @protected
  TwonlyConfig sse_decode_twonly_config(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs__Output_StreamSink_String_Sse_AnyhowException(
    FutureOr<RustStreamSink<String>> Function() self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_i_64_Output_opt_box_autoadd_announced_user_AnyhowException(
    FutureOr<AnnouncedUser?> Function(PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_i_64_Output_opt_list_list_prim_u_8_strict_AnyhowException(
    FutureOr<List<Uint8List>?> Function(PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_i_64_Output_opt_list_other_promotion_AnyhowException(
    FutureOr<List<OtherPromotion>?> Function(PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_i_64_Output_opt_list_prim_u_8_strict_AnyhowException(
    FutureOr<Uint8List?> Function(PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_i_64_announced_user_opt_box_autoadd_i_64_Output_bool_AnyhowException(
    FutureOr<bool> Function(PlatformInt64, AnnouncedUser, PlatformInt64?) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_i_64_i_64_list_prim_u_8_strict_Output_bool_AnyhowException(
    FutureOr<bool> Function(PlatformInt64, PlatformInt64, Uint8List) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_i_64_list_prim_u_8_strict_Output_bool_AnyhowException(
    FutureOr<bool> Function(PlatformInt64, Uint8List) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_list_list_prim_u_8_strict_Output_bool_AnyhowException(
    FutureOr<bool> Function(List<Uint8List>) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_list_prim_u_8_strict_Output_opt_list_prim_u_8_strict_AnyhowException(
    FutureOr<Uint8List?> Function(Uint8List) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_list_prim_u_8_strict_list_prim_u_8_strict_list_prim_u_8_strict_Output_bool_AnyhowException(
    FutureOr<bool> Function(Uint8List, Uint8List, Uint8List) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_other_promotion_Output_bool_AnyhowException(
    FutureOr<bool> Function(OtherPromotion) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_announced_user(AnnouncedUser self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_announced_user(
    AnnouncedUser self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_twonly_config(
    TwonlyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_user_discovery(
    FlutterUserDiscovery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_other_promotion(
    List<OtherPromotion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_announced_user(
    AnnouncedUser? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_list_prim_u_8_strict(
    List<Uint8List>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_other_promotion(
    List<OtherPromotion>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_other_promotion(
    OtherPromotion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_twonly_config(TwonlyConfig self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary();
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
