// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'frb_generated.dart';
import 'twonly/database/contact.dart';

// These functions are ignored because they are not marked as `pub`: `get_instance`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Twonly`

Future<void> initializeTwonly({required TwonlyConfig config}) =>
    RustLib.instance.api.crateTwonlyInitializeTwonly(config: config);

Future<List<Contact>> getAllContacts() =>
    RustLib.instance.api.crateTwonlyGetAllContacts();

class TwonlyConfig {
  const TwonlyConfig({
    required this.databasePath,
  });
  final String databasePath;

  @override
  int get hashCode => databasePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TwonlyConfig &&
          runtimeType == other.runtimeType &&
          databasePath == other.databasePath;
}
