// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PqcPreKeyInput {
  final PlatformInt64 eccPreKeyId;
  final Uint8List eccPreKey;
  final PlatformInt64 kyberPreKeyId;
  final Uint8List kyberPreKey;
  final Uint8List kyberPreKeySignature;

  const PqcPreKeyInput({
    required this.eccPreKeyId,
    required this.eccPreKey,
    required this.kyberPreKeyId,
    required this.kyberPreKey,
    required this.kyberPreKeySignature,
  });

  @override
  int get hashCode =>
      eccPreKeyId.hashCode ^
      eccPreKey.hashCode ^
      kyberPreKeyId.hashCode ^
      kyberPreKey.hashCode ^
      kyberPreKeySignature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PqcPreKeyInput &&
          runtimeType == other.runtimeType &&
          eccPreKeyId == other.eccPreKeyId &&
          eccPreKey == other.eccPreKey &&
          kyberPreKeyId == other.kyberPreKeyId &&
          kyberPreKey == other.kyberPreKey &&
          kyberPreKeySignature == other.kyberPreKeySignature;
}
